version: "3.9"
services: 
  frontend:
    image: sharedpaymentsfrontend
    ports:
      - "4200:80"
    depends_on:
    - backend
    expose:
      - "80"
  
  backend:
    image: sharedpaymentsbackend
    environment:
      - DATABASE_URL=mysqldb:3306
      - DATABASE_NAME:test
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: always

  mysqldb:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=admin,
      - MYSQL_PASSWORD=password
    expose:
      - "3306"
    restart: always
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3306"]
        interval: 30s
        timeout: 10s
        retries: 10