package com.sharedPayments.integration;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.sql.SQLException;

import org.junit.jupiter.api.Test;

import com.sharedPayments.model.UserEntity;
import com.sharedPayments.repository.UserInfraJpaRepository;

import jakarta.inject.Inject;

public class UserRepositoryIT extends GenericIT {

	@Inject
	private UserInfraJpaRepository userRepository;

	@Override
	protected long getInitialID() {
		return 100L;
	}

	private void saveUsersToRepository(UserEntity... users) {
		for (UserEntity u : users)
			this.userRepository.save(u);
	}

	@Test
	void givenOneNewUser_WhenSaved_ThenUsersTableContainsThatUser() throws SQLException {
		UserEntity user = UserEntity.builder().name("Fuencisla").build();
		user = this.userRepository.save(user);

		var users = this.getAllUsersFromDB();

		assertEquals(6, users.size());
		assertThat(users.get(5).getId(), is(100L));
		assertThat(users.get(5).getId(), is(user.getId()));
		assertThat(users.get(5).getName(), is(user.getName()));
	}

	@Test
	void givenOneNewUser_WhenSaved_ThenUsersTableContainsAll() throws SQLException {
		UserEntity user1 = UserEntity.builder().name("NewUser").build();
		this.saveUsersToRepository(user1);

		var users = this.getAllUsersFromDB();

		assertEquals(6, users.size());
		assertThat(users.get(4).getId(), is(5L));
		assertThat(users.get(4).getName(), is("Rebeca"));
		assertThat(users.get(5).getId(), is(user1.getId()));
		assertThat(users.get(5).getName(), is(user1.getName()));
	}

	@Test
	void givenSeveralNewUsers_WhenSaved_ThenAutoGeneratedIdIncreasesAccordingly() throws SQLException {
		this.saveUsersToRepository(
				UserEntity.builder().name("User100").build(),
				UserEntity.builder().name("User101").build(),
				UserEntity.builder().name("User102").build(),
				UserEntity.builder().name("User103").build());

		UserEntity userWithId104 = UserEntity.builder().name("User104").build();
		this.userRepository.save(userWithId104);
		var users = this.getAllUsersFromDB();

		assertEquals(10, users.size());
		assertThat(users.get(5).getId(), is(100L));
		assertThat(users.get(9).getId(), is(104L));

	}

	@Test
	void givenNoNewUsers_WhenFindAll_ThenListIsEmpty() throws SQLException {
		assertEquals(this.getAllUsersFromDB(), this.userRepository.findAll());
	}

	@Test
	void givenSeveralNewUsers_WhenFindAll_ThenListContainsAllUsers() throws SQLException {
		UserEntity[] dbUsers = { UserEntity.builder().name("George").build(), UserEntity.builder().name("Martha").build(), UserEntity.builder().name("Bilbo").build() };
		this.saveUsersToRepository(dbUsers);

		assertEquals(this.getAllUsersFromDB(), this.userRepository.findAll());
	}

	@Test
	void givenOneNewUser_WhenUpdateUserName_ThenDatabaseHasUpdatedData() throws SQLException {
		String newName = "NewName";
		this.saveUsersToRepository(UserEntity.builder().name("OldName").build());

		UserEntity user = this.userRepository.findById(100L).get();
		user.setName(newName);
		user = this.userRepository.update(user);
		var users = this.getAllUsersFromDB();

		assertEquals(6, users.size());
		assertThat(users.get(5).getId(), is(100L));
		assertThat(users.get(5).getName(), is(newName));
	}

}
