micronaut:
  application:
    name: sharedPayments
  server:
    port: ${SERVER_PORT:8080}
    
netty:
  default:
    allocator:
      max-order: 3

micronaut:
    server:
        cors:
            enabled: true

datasources:
  default:
    url: jdbc:mysql://${DATABASE_URL:`localhost:3306`}/${DATABASE_NAME:test}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
    db-type: mysql
    dialect: MySQL
  
test-resources:
  containers:
    mysql:
      image-name: mysql:8

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true