name: Continuous Integration release workflow

on: 
  # push:
  #  branches: 
  #    - main
  workflow_dispatch:

jobs:
  releaseTestArtifacts:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: booklibrary
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Into backend directory
        run: cd backend/parent-project
      - name: Unitary & Integration tests
        run: mvn clean install -P IT
      - name: Build
        run: mvn package

      - name: Generate pom version tag
        run: echo ::set-output name=pom-version::$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)
        id: generate-pom-tag
      - name: Build Docker image
        run: cd ../.. && ./buildDockerImages.sh
        
      - name: Adding .RC1 suffix
        run: mvn versions:set -DnewVersion=${{ steps.generate-pom-tag.outputs.pom-version }}.RC1
        shell: bash
      - name: Publish maven artifact
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
