name: Continuous Integration release workflow

on: 
  # push:
  #  branches: 
  #    - main
  workflow_dispatch:

jobs:
  releaseTestArtifacts:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: booklibrary
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Into backend directory
        run: cd backend/parent-project
      - name: Unitary & Integration tests
        run: mvn clean install -P IT
      - name: Build
        run: mvn package

      - name: Generate pom version ouput
        run: echo ::set-output name=pom-version::$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout) \
             && VERSION=$(echo $(mvn -q help:evaluate -Dexpression=project.version -DforceStdout) | sed 's/-SNAPSHOT*//' \
             && echo $VERSION | awk -F. '/[0-9]+\./{$NF++;print}' OFS=.
        id: generate-pom-tag
      - name: Build Docker image
        run: cd ../.. && ./buildDockerImages.sh

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            startup/target/startup.jar
        
      - name: Adding .RC1 suffix
        run: mvn versions:set -DnewVersion=${{ steps.generate-pom-tag.outputs.pom-version }}
        shell: bash
      - name: Print new version
        run: echo $(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)
