name: Continuous Integration release workflow

on: 
  # push:
  #  branches: 
  #    - main
  workflow_dispatch:

jobs:
  continuousIntegration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Unitary & Integration tests
        working-directory: ./backend/parent-project
        run: mvn clean install -P IT
      - name: Build
        working-directory: ./backend/parent-project
        run: mvn package

      - name: Generate pom version ouput
        working-directory: ./backend/parent-project
        run: echo ::set-output name=pom-version::$(echo $(mvn -q help:evaluate -Dexpression=project.version -DforceStdout) | sed 's/-SNAPSHOT*//' | awk -F. '/[0-9]+\./{$NF++;print}' OFS=.)
        id: generate-pom-tag

      - name: Create release
        uses: softprops/action-gh-release@v1
      #  if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: testRelease
          prerelease: true
          files: |
            backend/parent-project/startup/target/startup.jar
        
      - name: Updating version
        working-directory: ./backend/parent-project
        run: mvn versions:set -DnewVersion=${{ steps.generate-pom-tag.outputs.pom-version }}
        shell: bash
      - name: Print new version
        working-directory: ./backend/parent-project
        run: echo $(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)
